### ISSUE TITLE
Make this more user-friendly + give it a unique name

### ISSUE THREAD

**Issue by Pentaphon** [depler/transmission-vs#1]
Hi, this project seems to be quite promising but there's 2 issues I see getting in the way of adoption. 

1) It needs to have a unique name. Yes, this seems unimportant but if you're doing something different, a unique name goes a long way in getting people to use it. Nothing flashy, but the same way cfpp2p has transmission-daemon-cygwin really makes it easier to find on google and differentiates it from the main project without going too far. Maybe call it transmission-service or transmission-vs or transmission-minimal or something like that. 

2) The project needs to become more user-friendly. Right now, the average user has no idea what to do with all those bat files. They will either ask you what they need to do or just give up, which won't help you get users. I suggest making this project as simple as possible. Perhaps you can have this run in a simple, open source installer with a simple UI? Reduce the number of bat files? Make the web-UI just work out of the box? You may not agree with any of these suggestions and I don't blame you, but overall, the advice I have is to make this project as simple to run as possible and anything you can do to streamline how a user would run this would really help your project. 

I know this isn't a bug report but since there's no other issues, this can be a discussion to perhaps spur a way to take your project to another level.

**Comment by depler** [comment]
`add a "start_background.bat" and "stop_background.bat" so that people don't need to bother with a service`

Why someone needs to run it in background for a while and manually close it later? I mean, if you just want to see "how it works" you can run foreground. And the background task is intended to be continuous, there is no need to stop it - it has extremely low memory and power consumption.
